[env]
platform = espressif32
; board_build.partitions = huge_app.csv
framework = arduino
monitor_speed = 115200

lib_deps=
  Madgwick=https://github.com/arduino-libraries/MadgwickAHRS
  EspSoftwareSerial=https://github.com/plerup/espsoftwareserial
  lovyan03/LovyanGFX@^1.2.19
  jrowberg/I2Cdevlib-Core@^1.0.0
  jrowberg/I2Cdevlib-MPU6050@^1.0.0
  jrowberg/I2Cdevlib-HMC5883L@^1.0.0
  jrowberg/I2Cdevlib-BMP085@^1.0.0


[env:YCD]
board = esp32dev

build_flags =
  -DUSE_HARDWARE_IMU=1
  -DCORE_DEBUG_LEVEL=5
  -DMAG_USE_QMC5883P=1
  -DTFT_BACKLIGHT=27
  -DTFT_DC=2
  -DTFT_CS=15
  -DTFT_RST=0
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DLED_RED=4
  -DLED_GREEN=17
  -DLED_BLUE=16
  -DBOOT_BTN=0
  -DBOARD=BOARD_YCD

[env:UEDX4848]
board = esp32s3box

build_flags =
  -DUSE_DEMO=1
  -DBOOT_BTN=-1
  -DBOARD=BOARD_UEDX4848