; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
; board_build.partitions = huge_app.csv
framework = arduino
monitor_speed = 115200

build_flags =
  -DCORE_DEBUG_LEVEL=5
  -DMAG_USE_QMC5883P=1
  -DTFT_BACKLIGHT=27
  -DTFT_DC=2
  -DTFT_CS=15
  -DTFT_RST=0
  -DTFT_MISO=12
  -DTFT_MOSI=13
  -DTFT_SCLK=14
  -DLED_RED=4
  -DLED_GREEN=17
  -DLED_BLUE=16
  -DBOOT_BTN=0

lib_deps=
  LovyanGFX=https://github.com/lovyan03/LovyanGFX
  Madgwick=https://github.com/arduino-libraries/MadgwickAHRS
  EspSoftwareSerial=https://github.com/plerup/espsoftwareserial
  jrowberg/I2Cdevlib-Core@^1.0.0
  jrowberg/I2Cdevlib-MPU6050@^1.0.0
  jrowberg/I2Cdevlib-HMC5883L@^1.0.0
  jrowberg/I2Cdevlib-BMP085@^1.0.0
